# Generated by Django 5.0.4 on 2024-04-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_code", models.CharField(max_length=10)),
                ("cost_share_rate", models.FloatField()),
                ("allowed_spend", models.CharField(max_length=100)),
            ],
        ),
    ]
