# Generated by Django 5.0.4 on 2024-04-07 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ads_run", models.IntegerField()),
                ("actual_spend", models.FloatField()),
                (
                    "ad_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.adtype"
                    ),
                ),
            ],
        ),
    ]
