# Generated by Django 5.0.4 on 2024-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="adentry",
            name="cost_sharing",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="adentry",
            name="reimbursement",
            field=models.FloatField(default=0.0),
        ),
    ]
