# Generated by Django 5.0.4 on 2024-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_adentry_cost_sharing_adentry_reimbursement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adentry",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
